version: 2

updates:
  # Workflows and their actions
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/setup
    schedule:
      interval: weekly
      day: monday
    groups:
      actions:
        patterns: ['*']

  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      dart:
        patterns: ['*']

  # base images in Dockerfile
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      images:
        patterns: ['*']

  # fastlane (for releases)
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      ruby:
        patterns: ['*']

  # Android build
  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: weekly
      day: monday
    groups:
      android:
        patterns: ['*']
